const API = localStorage.getItem("healthApiUrl") || "http://127.0.0.1:8000";
const state = {
  active: "overview", records: [], timeline: [], analytics: { trends: [], signals: [] }, audit: [],
  user: null, token: localStorage.getItem("healthToken") || "", loading: true,
  search: "", searchResults: [], conversationId: null, chat: [], literature: [],
};
const style = document.createElement("link"); style.rel = "stylesheet"; style.href = "/src/styles.css"; document.head.appendChild(style);

const $ = (selector) => document.querySelector(selector);
const esc = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
const date = (value) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Date not recorded";
const shortId = (value) => value ? `${value.slice(0, 6)}...${value.slice(-4)}` : "-";
const initials = (value) => (value || "Guest").slice(0, 2).toUpperCase();

async function api(path, options = {}) {
  const headers = new Headers(options.headers || {});
  if (state.token) headers.set("Authorization", `Bearer ${state.token}`);
  if (options.body && !(options.body instanceof FormData) && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
  const response = await fetch(`${API}${path}`, { ...options, headers });
  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    const detail = Array.isArray(body.detail)
      ? body.detail.map((item) => item.msg || item.detail || JSON.stringify(item)).join("; ")
      : body.detail;
    const error = new Error(detail || `Request failed (${response.status})`);
    error.status = response.status;
    throw error;
  }
  return response.status === 204 ? null : response.json();
}

function icon(name) {
  const icons = { overview: "▦", records: "▤", timeline: "⌁", insights: "⌁", literature: "⊕", audit: "◌", search: "⌕", upload: "↑", send: "→", settings: "⚙", close: "×", arrow: "↗", lock: "▣" };
  return `<span class="icon" aria-hidden="true">${icons[name] || "·"}</span>`;
}

function shell() {
  document.querySelector("#app").innerHTML = `
    <div class="app-shell">
      <aside class="sidebar">
        <div class="brand"><span class="brand-mark">+</span><div><strong>health record</strong><small>private workspace</small></div></div>
        <div class="patient-switcher"><span class="avatar">${initials(state.user?.username || "me")}</span><div><small>ACTIVE PATIENT</small><strong>${esc(state.user?.username || "Personal record")}</strong></div><span class="chevron">⌄</span></div>
        <nav class="main-nav" aria-label="Main navigation">
          ${navItem("overview", "Overview", "overview")}
          ${navItem("records", "My records", "records")}
          ${navItem("timeline", "Timeline", "timeline")}
          ${navItem("insights", "Clinical insights", "insights")}
          ${navItem("literature", "Medical literature", "literature")}
        </nav>
        <div class="nav-label">ACCOUNT</div>
        ${navItem("audit", "Privacy & activity", "audit")}
        <div class="sidebar-bottom"><div class="privacy-note">${icon("lock")}<div><strong>Your records stay yours.</strong><span>Every action is logged privately.</span></div></div><button class="quiet-button" id="logout">Sign out ${icon("arrow")}</button></div>
      </aside>
      <main class="main-area">
        <header class="topbar"><div class="breadcrumb"><span>Personal health</span><b>/</b><strong>${labelFor(state.active)}</strong></div><div class="top-actions"><button class="round-button" id="global-search" aria-label="Search records">${icon("search")}</button><span class="status-dot"></span><span class="sync-label">Local workspace</span><button class="user-menu" id="user-menu"><span class="mini-avatar">${initials(state.user?.username || "me")}</span>${esc(state.user?.username || "Guest")} <span>⌄</span></button></div></header>
        <div class="page-content" id="page-content"></div>
      </main>
      <aside class="chat-rail"><div class="chat-header"><div><small>RECORD ASSISTANT</small><h2>Ask your records</h2></div><span class="online-indicator">●</span></div><div class="chat-context"><span class="context-icon">✦</span><span>Answers are grounded in your uploaded records</span></div><div class="chat-messages" id="chat-messages"><div class="assistant-message"><span class="message-kicker">READY WHEN YOU ARE</span><p>Ask about a result, a date, or a pattern across your records.</p><span class="message-time">Now</span></div></div><form class="chat-form" id="chat-form"><textarea id="chat-input" placeholder="Ask a question..." rows="2"></textarea><button type="submit" aria-label="Send question">${icon("send")}</button></form><div class="chat-disclaimer">Not medical advice. For urgent symptoms, contact local emergency services.</div></aside>
    </div>
    <div class="toast" id="toast" role="status"></div>
    <div class="modal-backdrop hidden" id="modal"></div>`;
  bindShell();
}

function navItem(key, text, iconName) { return `<button class="nav-item ${state.active === key ? "active" : ""}" data-view="${key}">${icon(iconName)}<span>${text}</span>${key === "insights" && state.analytics.signals?.length ? `<em>${state.analytics.signals.length}</em>` : ""}</button>`; }
function labelFor(view) { return ({ overview: "Overview", records: "My records", timeline: "Timeline", insights: "Clinical insights", literature: "Medical literature", audit: "Privacy & activity" })[view]; }

function bindShell() {
  document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { state.active = button.dataset.view; render(); }));
  $("#chat-form").addEventListener("submit", sendChat);
  $("#logout").addEventListener("click", () => { localStorage.removeItem("healthToken"); state.token = ""; state.user = null; renderAuth(); });
  $("#global-search").addEventListener("click", () => { state.active = "records"; render(); setTimeout(() => $("#record-search")?.focus(), 50); });
  $("#user-menu").addEventListener("click", () => showProfileMenu());
  document.querySelectorAll("[data-record]").forEach((button) => button.addEventListener("click", () => openRecord(button.dataset.record)));
}

function render() { shell(); const page = ({overview: renderOverview, records: renderRecords, timeline: renderTimeline, insights: renderInsights, literature: renderLiterature, audit: renderAudit})[state.active]; page(); }

function renderOverview() {
  const signals = state.analytics.signals || [], latest = state.records[0];
  const reviewClass = signals.length ? "coral" : "green";
  const reviewCopy = signals.length ? "Worth discussing with a clinician" : "No configured signals found";
  const focusMarkup = signals.length ? signalRow(signals[0]) : `<div class="empty-focus"><span class="focus-symbol">✓</span><strong>No threshold signals</strong><p>As more records arrive, patterns and configured review signals will appear here.</p></div>`;
  const focusPill = signals.length ? `<span class="alert-pill">${signals.length} to review</span>` : `<span class="soft-pill">Clear</span>`;
  $("#page-content").innerHTML = `<section class="page-heading"><div><span class="eyebrow">PATIENT OVERVIEW</span><h1>Your health, in context.</h1><p>A clear view of what is in your records, what has changed, and what deserves a closer look.</p></div><button class="primary-button" id="upload-top">${icon("upload")} Add a record</button></section>
  <div class="metric-grid"><div class="metric-card"><span class="metric-label">RECORDS ON FILE</span><strong>${state.records.length}</strong><span class="metric-foot">${latest ? `Last added ${date(latest.created_at)}` : "Start by adding a record"}</span></div><div class="metric-card teal"><span class="metric-label">TIMELINE EVENTS</span><strong>${state.timeline.length}</strong><span class="metric-foot">Normalized clinical entries</span></div><div class="metric-card ${reviewClass}"><span class="metric-label">REVIEW SIGNALS</span><strong>${signals.length}</strong><span class="metric-foot">${reviewCopy}</span></div><div class="metric-card lavender"><span class="metric-label">LAST SYNC</span><strong>Now</strong><span class="metric-foot">Local workspace is current</span></div></div>
  <div class="overview-grid"><section class="panel timeline-preview"><div class="panel-heading"><div><span class="eyebrow">AT A GLANCE</span><h2>Recent timeline</h2></div><button class="text-button" data-view="timeline">View full timeline ${icon("arrow")}</button></div>${timelineRows(state.timeline.slice(0, 4))}</section><section class="panel focus-panel"><div class="panel-heading"><div><span class="eyebrow">TODAY'S FOCUS</span><h2>Clinical insights</h2></div>${focusPill}</div>${focusMarkup}<button class="outline-button full" data-view="insights">Open insights ${icon("arrow")}</button></section></div>
  <section class="panel source-strip"><div class="source-copy"><span class="eyebrow">WORKING WITH YOUR RECORDS</span><h2>Keep the paper trail together.</h2><p>Upload a lab report, prescription, scan, or note. We extract the useful facts while keeping the original source available.</p></div><div class="drop-zone" id="drop-zone"><span class="upload-glyph">↑</span><strong>Drop a file here</strong><span>PDF, text, or image · up to 25 MB</span><input type="file" id="file-input" hidden /></div></section>`;
  $("#upload-top").addEventListener("click", () => $("#file-input")?.click());
  $("#file-input")?.addEventListener("change", (event) => upload(event.target.files[0]));
  $("#drop-zone")?.addEventListener("click", () => $("#file-input")?.click());
  $("#drop-zone")?.addEventListener("dragover", (e) => { e.preventDefault(); e.currentTarget.classList.add("dragging"); });
  $("#drop-zone")?.addEventListener("dragleave", (e) => e.currentTarget.classList.remove("dragging"));
  $("#drop-zone")?.addEventListener("drop", (e) => { e.preventDefault(); e.currentTarget.classList.remove("dragging"); upload(e.dataTransfer.files[0]); });
  document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { state.active = button.dataset.view; render(); }));
}

function timelineRows(items) { if (!items.length) return `<div class="empty-state"><span>⌁</span><strong>Your timeline will take shape here.</strong><p>Upload your first health record to begin.</p></div>`; return `<div class="timeline-list">${items.map((item) => `<article class="timeline-entry"><div class="timeline-row"><div class="date-column"><strong>${item.event_date ? new Date(item.event_date).toLocaleDateString(undefined, { day: "2-digit", month: "short" }) : "—"}</strong><span>${item.event_date ? new Date(item.event_date).getFullYear() : "Undated"}</span></div><div class="timeline-dot"></div><div class="timeline-info"><strong>${esc(item.title || item.document_type.replaceAll("_", " "))}</strong><span>${esc(item.filename)} · ${item.observations?.length || 0} observations</span></div><button class="row-arrow" data-record="${item.record_id}" aria-label="Open source record">${icon("arrow")}</button></div><div class="timeline-detail"><div class="detail-label">${esc(item.document_type.replaceAll("_", " "))}</div>${item.observations?.length ? `<div class="observation-chips">${item.observations.map((observation) => `<span class="observation-chip"><strong>${esc(observation.name.replaceAll("_", " "))}</strong><b>${esc(observation.value)}${observation.unit ? ` ${esc(observation.unit)}` : ""}</b>${observation.observed_on ? `<small>${date(observation.observed_on)}</small>` : ""}</span>`).join("")}</div>` : `<span class="no-observations">No normalized measurements in this document.</span>`}</div></article>`).join("")}</div>`; }
function signalRow(signal) { return `<div class="signal-row"><span class="signal-icon">!</span><div><strong>${esc(signal.title)}</strong><p>${esc(signal.detail)}</p><span class="signal-meta">${esc(signal.metric.replaceAll("_", " "))} · ${date(signal.observed_on)}</span></div></div>`; }

function renderRecords() { $("#page-content").innerHTML = `<section class="page-heading compact"><div><span class="eyebrow">SOURCE LIBRARY</span><h1>My records</h1><p>Original documents and the normalized information extracted from them.</p></div><button class="primary-button" id="upload-record">${icon("upload")} Add record</button></section><div class="record-toolbar"><label class="search-box">${icon("search")}<input id="record-search" placeholder="Search across your records" value="${esc(state.search)}" /><kbd>⌘ K</kbd></label><div class="toolbar-meta">${state.records.length} document${state.records.length === 1 ? "" : "s"}</div></div><div id="record-results" class="record-grid">${recordCards(state.records)}</div>`; $("#upload-record").addEventListener("click", openUploadModal); $("#record-search").addEventListener("input", (event) => { state.search = event.target.value; clearTimeout(window.searchTimer); window.searchTimer = setTimeout(searchRecords, 300); }); }
function recordCards(records) { if (!records.length) return `<div class="empty-state wide"><span>▤</span><strong>No records yet</strong><p>Upload a document and your extracted facts will appear here.</p></div>`; return records.map((record) => `<article class="record-card"><div class="record-card-top"><span class="file-type ${record.source_type}">${record.source_type.toUpperCase()}</span><span class="status-badge ${record.status}">${record.status}</span></div><h3>${esc(record.filename)}</h3><p>${record.extracted_characters ? `${record.extracted_characters.toLocaleString()} characters extracted` : "Awaiting extraction"}</p><div class="record-card-bottom"><span>${date(record.created_at)}</span><button class="row-arrow" data-record="${record.id}" aria-label="Open record">${icon("arrow")}</button></div></article>`).join(""); }

function renderTimeline() { $("#page-content").innerHTML = `<section class="page-heading compact"><div><span class="eyebrow">NORMALIZED RECORDS</span><h1>Timeline</h1><p>A chronological view assembled from the documents you have added.</p></div><div class="view-note">${icon("lock")} Personal workspace</div></section><section class="panel full-timeline"><div class="timeline-header"><div><span class="eyebrow">${state.timeline.length} EVENTS</span><h2>Clinical history</h2></div><span class="legend"><i></i> extracted from source records</span></div>${timelineRows(state.timeline)}</section>`; }

function renderInsights() { const trends = state.analytics.trends || []; $("#page-content").innerHTML = `<section class="page-heading compact"><div><span class="eyebrow">PATTERN REVIEW</span><h1>Clinical insights</h1><p>Transparent trends from normalized observations. These are review signals, not diagnoses.</p></div><span class="insight-badge">${icon("lock")} Evidence linked</span></section><div class="insights-layout"><section class="panel trend-panel"><div class="panel-heading"><div><span class="eyebrow">MEASUREMENTS OVER TIME</span><h2>Observed trends</h2></div><span class="soft-pill">${trends.length} metrics</span></div>${trends.length ? trends.map(trendCard).join("") : `<div class="empty-state"><span>⌁</span><strong>Not enough data yet</strong><p>Repeated observations across records will become trends here.</p></div>`}</section><section class="panel signals-panel"><div class="panel-heading"><div><span class="eyebrow">CONFIGURED REVIEW</span><h2>Signals</h2></div><span class="alert-pill">${state.analytics.signals?.length || 0}</span></div>${state.analytics.signals?.length ? state.analytics.signals.map(signalRow).join("") : `<div class="empty-focus"><span class="focus-symbol">✓</span><strong>Nothing flagged</strong><p>No configured thresholds were crossed in the normalized records.</p></div>`}</section></div>`; }
function trendCard(trend) { const values = trend.points.map((point) => point.value), max = Math.max(...values), min = Math.min(...values), range = max - min || 1; const bars = values.slice(-12).map((value) => `<span style="height:${Math.max(18, ((value - min) / range) * 65 + 18)}%"></span>`).join(""); return `<div class="trend-card"><div class="trend-label"><div><strong>${esc(trend.metric.replaceAll("_", " "))}</strong><span>${trend.points.length} observation${trend.points.length === 1 ? "" : "s"}</span></div><span class="direction ${trend.direction}">${trend.direction.replaceAll("_", " ")}</span></div><div class="trend-visual"><div class="bars">${bars}</div><div class="trend-number"><strong>${trend.latest_value ?? "—"}</strong><span>${esc(trend.points.at(-1)?.unit || "latest")}</span></div></div><div class="trend-foot"><span>${trend.points[0]?.observed_on ? date(trend.points[0].observed_on) : ""}</span><span>${trend.change != null ? `${trend.change > 0 ? "+" : ""}${trend.change} change` : "Single observation"}</span></div></div>`; }

function renderLiterature() { $("#page-content").innerHTML = `<section class="page-heading compact"><div><span class="eyebrow">EXTERNAL EVIDENCE</span><h1>Medical literature</h1><p>Search PubMed for context beyond your personal records. Results stay separate and are cited.</p></div><span class="source-chip">PUBMED</span></section><section class="literature-layout"><section class="panel literature-search"><div class="literature-intro"><span class="large-symbol">⊕</span><div><h2>Find clinical context</h2><p>Search by condition, symptom, medication, or question.</p></div></div><form id="literature-form" class="wide-search"><input id="literature-input" placeholder="e.g. sleep and blood pressure" required /><button class="primary-button">Search ${icon("search")}</button></form><div id="literature-results">${literatureCards(state.literature)}</div></section><section class="panel literature-note"><span class="eyebrow">A NOTE ON SOURCES</span><h2>Read the evidence in context.</h2><p>Literature search helps you prepare better questions. It does not replace clinical judgment or turn a paper into a recommendation for you.</p><div class="source-list"><span>⌁</span><div><strong>PubMed indexed</strong><small>Titles, abstracts, and citations</small></div></div><div class="source-list"><span>↗</span><div><strong>Direct citations</strong><small>Open the original record</small></div></div></section></section>`; $("#literature-form").addEventListener("submit", searchLiterature); }
function literatureCards(items) { if (!items.length) return `<div class="empty-state literature-empty"><span>⊕</span><strong>Search the literature</strong><p>Your results will appear with their PubMed citation IDs.</p></div>`; return items.map((item) => `<article class="literature-card"><div><span class="citation-id">${esc(item.citation_id)}</span><h3>${esc(item.filename)}</h3><p>${esc(item.content)}</p></div>${item.source_url ? `<a href="${esc(item.source_url)}" target="_blank" rel="noreferrer">Open source ${icon("arrow")}</a>` : ""}</article>`).join(""); }

function renderAudit() { $("#page-content").innerHTML = `<section class="page-heading compact"><div><span class="eyebrow">PRIVACY CONTROL</span><h1>Privacy & activity</h1><p>A private record of access and actions in this workspace. Clinical text is not copied into event metadata.</p></div><span class="secure-chip">${icon("lock")} Protected</span></section><section class="panel audit-panel"><div class="panel-heading"><div><span class="eyebrow">YOUR ACTIVITY</span><h2>Audit trail</h2></div><span class="soft-pill">${state.audit.length} events</span></div>${state.audit.length ? `<div class="audit-table"><div class="audit-head"><span>Action</span><span>Resource</span><span>When</span></div>${state.audit.map((event) => `<div class="audit-row"><span><i class="audit-dot"></i><strong>${esc(event.action)}</strong></span><span>${esc(event.resource_type)} ${event.resource_id ? `<small>${shortId(event.resource_id)}</small>` : ""}</span><span>${date(event.created_at)}</span></div>`).join("")}</div>` : `<div class="empty-state"><span>◌</span><strong>No activity yet</strong><p>Actions you take in this workspace will appear here.</p></div>`}</section>`; }

async function loadData() { try { const [records, timeline, analytics, audit] = await Promise.all([api("/api/v1/records"), api("/api/v1/timeline"), api("/api/v1/analytics"), api("/api/v1/audit")]); state.records = records.items || []; state.timeline = timeline.events || []; state.analytics = analytics; state.audit = audit.events || []; state.loading = false; render(); } catch (error) { if (error.status === 401) return renderAuth(); toast(error.message); state.loading = false; render(); } }
async function searchRecords() { const query = $("#record-search")?.value.trim(); if (!query) { $("#record-results").innerHTML = recordCards(state.records); return; } try { const response = await api(`/api/v1/search?q=${encodeURIComponent(query)}&limit=10`); state.searchResults = response.results || []; $("#record-results").innerHTML = state.searchResults.length ? `<div class="search-results wide">${state.searchResults.map((item) => `<article class="evidence-card"><span class="citation-id">${esc(item.citation_id)}</span><h3>${esc(item.filename)}</h3><p>${esc(item.content)}</p><span class="score">Match ${Math.round(item.score * 100)}%</span></article>`).join("")}</div>` : `<div class="empty-state wide"><span>⌕</span><strong>No matching evidence</strong><p>Try a symptom, result, or phrase from a document.</p></div>`; } catch (error) { toast(error.message); } }
async function searchLiterature(event) { event.preventDefault(); const input = $("#literature-input"), button = $("#literature-form button"), query = input.value.trim(); if (!query) return; button.disabled = true; button.textContent = "Searching..."; try { const response = await api(`/api/v1/literature/search?q=${encodeURIComponent(query)}&limit=5`); state.literature = response.results || []; $("#literature-results").innerHTML = literatureCards(state.literature); toast(`${state.literature.length} PubMed result${state.literature.length === 1 ? "" : "s"} found`); } catch (error) { toast(error.message); } finally { button.disabled = false; button.innerHTML = `Search ${icon("search")}`; } }
async function sendChat(event) { event.preventDefault(); const input = $("#chat-input"), question = input.value.trim(); if (!question) return; addChat("user", question); input.value = ""; const button = $("#chat-form button"); button.disabled = true; try { const result = await api("/api/v1/ask", { method: "POST", body: JSON.stringify({ question, conversation_id: state.conversationId, limit: 5 }) }); state.conversationId = result.conversation_id; await streamChat("assistant", result.answer, result.citations, result.safety_level); } catch (error) { addChat("assistant", error.message); } finally { button.disabled = false; } }
function richText(text) { return esc(text).replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/^### (.*)$/gm, "<strong class=\"answer-heading\">$1</strong>").replace(/\n/g, "<br>"); }
function addChat(role, text, citations = [], safety = "normal") { const list = $("#chat-messages"); const item = document.createElement("div"); item.className = `${role}-message ${safety === "urgent" ? "urgent" : ""}`; item.innerHTML = `<span class="message-kicker">${role === "user" ? "YOU" : safety === "urgent" ? "SAFETY CHECK" : "RECORD ASSISTANT"}</span><p>${role === "assistant" ? richText(text) : esc(text)}</p>${citations.length ? `<div class="chat-citations">${citations.slice(0, 3).map((c) => `<span>${esc(c.citation_id)}</span>`).join("")}</div>` : ""}<span class="message-time">Now</span>`; list.appendChild(item); list.scrollTop = list.scrollHeight; }
function streamChat(role, text, citations = [], safety = "normal") { return new Promise((resolve) => { const list = $("#chat-messages"), item = document.createElement("div"); item.className = `${role}-message ${safety === "urgent" ? "urgent" : ""}`; item.innerHTML = `<span class="message-kicker">${safety === "urgent" ? "SAFETY CHECK" : "RECORD ASSISTANT"}</span><p class="streaming-answer"></p><span class="message-time">Writing...</span>`; list.appendChild(item); const output = item.querySelector(".streaming-answer"), step = Math.max(2, Math.ceil(text.length / 90)); let index = 0; const timer = setInterval(() => { index = Math.min(text.length, index + step); output.innerHTML = richText(text.slice(0, index)); list.scrollTop = list.scrollHeight; if (index >= text.length) { clearInterval(timer); item.querySelector(".message-time").textContent = "Now"; if (citations.length) { const citationBox = document.createElement("div"); citationBox.className = "chat-citations"; citationBox.innerHTML = citations.slice(0, 3).map((c) => `<span>${esc(c.citation_id)}</span>`).join(""); item.insertBefore(citationBox, item.querySelector(".message-time")); } resolve(); } }, 18); }); }
async function upload(file) { if (!file) return; const form = new FormData(); form.append("file", file); toast(`Uploading ${file.name}...`); try { await api("/api/v1/records", { method: "POST", body: form }); toast("Record added and normalized"); await loadData(); } catch (error) { toast(error.message); } }
function openUploadModal() { $("#modal").classList.remove("hidden"); $("#modal").innerHTML = `<div class="modal"><button class="modal-close" id="modal-close">×</button><span class="eyebrow">ADD TO SOURCE LIBRARY</span><h2>Upload a health record</h2><p>PDFs, notes, lab results, prescriptions, and image scans are supported.</p><label class="modal-drop" id="modal-drop"><span class="upload-glyph">↑</span><strong>Choose a file</strong><span>or drag it here</span><input type="file" id="modal-file" hidden /></label><div class="modal-foot"><span>${icon("lock")} Original files stay in your private workspace.</span></div></div>`; $("#modal-close").onclick = closeModal; $("#modal-file").onchange = (e) => { closeModal(); upload(e.target.files[0]); }; $("#modal-drop").onclick = () => $("#modal-file").click(); }
function closeModal() { $("#modal").classList.add("hidden"); }
function showProfileMenu() { toast(`Signed in as ${state.user?.username || "development"}`); }
async function openRecord(recordId) {
  try {
    const record = await api(`/api/v1/records/${recordId}`);
    $("#modal").classList.remove("hidden");
    const observations = record.structured?.observations || [];
    $("#modal").innerHTML = `<div class="modal record-detail-modal"><button class="modal-close" id="modal-close">×</button><div class="record-detail-top"><span class="file-type ${record.source_type}">${record.source_type.toUpperCase()}</span><span class="status-badge ${record.status}">${record.status}</span></div><span class="eyebrow">SOURCE RECORD</span><h2>${esc(record.filename)}</h2><p class="detail-meta">Added ${date(record.created_at)} · ${record.extracted_characters?.toLocaleString() || 0} extracted characters</p><div class="detail-section"><span class="eyebrow">NORMALIZED OBSERVATIONS</span>${observations.length ? `<div class="observation-list">${observations.map((item) => `<div><strong>${esc(item.name.replaceAll("_", " "))}</strong><span>${esc(item.value)} ${esc(item.unit || "")}</span></div>`).join("")}</div>` : `<p class="detail-empty">No structured observations were detected in this record.</p>`}</div><div class="detail-section"><span class="eyebrow">EXTRACTED TEXT</span><pre class="extracted-text">${esc(record.text || record.error || "No text available")}</pre></div><div class="modal-foot">${icon("lock")} Original source remains in your private workspace.</div></div>`;
    $("#modal-close").onclick = closeModal;
  } catch (error) { toast(error.message); }
}
function toast(message) { const element = $("#toast"); if (!element) return; element.textContent = message; element.classList.add("show"); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => element.classList.remove("show"), 3500); }

function renderAuth() { document.querySelector("#app").innerHTML = `<main class="auth-page"><div class="auth-brand"><span class="brand-mark">+</span><strong>health record</strong></div><section class="auth-card"><span class="eyebrow">PRIVATE HEALTH WORKSPACE</span><h1>Make sense of the record you already have.</h1><p>Bring your reports together, follow changes over time, and ask grounded questions with your sources in view.</p><form id="auth-form"><label>Username<input id="auth-username" required minlength="3" autocomplete="username" /></label><label>Password<input id="auth-password" required minlength="8" type="password" autocomplete="current-password" /></label><button class="primary-button full" type="submit">Sign in ${icon("arrow")}</button><p class="auth-error" id="auth-error"></p></form><div class="auth-switch">New here? <button id="switch-auth">Create a workspace</button></div></section><div class="auth-note">${icon("lock")} Your information stays inside your configured health-record workspace.</div></main>`; let registering = false; $("#switch-auth").onclick = () => { registering = !registering; $("#switch-auth").textContent = registering ? "I already have an account" : "Create a workspace"; $("#auth-form .primary-button").innerHTML = registering ? `Create workspace ${icon("arrow")}` : `Sign in ${icon("arrow")}`; $(".auth-card h1").textContent = registering ? "Start with a private workspace." : "Make sense of the record you already have."; }; $("#auth-form").onsubmit = async (event) => { event.preventDefault(); const username = $("#auth-username").value, password = $("#auth-password").value; try { if (registering) await api("/api/v1/auth/register", { method: "POST", body: JSON.stringify({ username, password }) }); const form = new URLSearchParams({ username, password }); const result = await api("/api/v1/auth/token", { method: "POST", body: form, headers: { "Content-Type": "application/x-www-form-urlencoded" } }); state.token = result.access_token; localStorage.setItem("healthToken", state.token); state.user = await api("/api/v1/auth/me"); loadData(); } catch (error) { $("#auth-error").textContent = error.message; } }; }

async function boot() { if (!state.token) return renderAuth(); try { state.user = await api("/api/v1/auth/me"); await loadData(); } catch { renderAuth(); } }
boot();
